# DocuAgent Default Configuration

device: "auto"  # "cuda" | "cpu" | "auto"
dpi: 220

layout:
  model: "pp_doclayout_l"  # "pp_doclayout_l" | "yolov10"
  conf_threshold: 0.25
  classes: ["Text", "Title", "List", "Table", "Figure"]

ocr:
  lang: "ml"  # multilingual

langid:
  model_path: ".cache/lid.176.bin"

vlm:
  model: "Qwen/Qwen2-VL-7B-Instruct"

describe:
  batch_size: 2

io:
  cache_dir: ".cache"
  debug_dir: "./debug"

runtime:
  num_workers: 4

# Training configuration
train:
  backend: "yolov10"  # "yolov10" | "pp_doclayout_l"
  data_root: "./data"
  classes: ["Text", "Title", "List", "Table", "Figure"]
  imgsz: 960
  epochs: 60
  batch: 16
  lr0: 0.01
  conf_thr: 0.25
  iou_nms: 0.5
  val_every: 1
  yolo_model: "yolov10n.pt"  # changeable to s/m/l

# Evaluation configuration
eval:
  cer_wer: true
  bleu_bertscore: true
  save_overlays: true
  topk_errors: 150

# Paths
paths:
  weights_dir: "./weights"
  runs_dir: "./runs"
  debug_dir: "./debug"
